### ISSUE TITLE
Allow installation with current Composer versions (plugin API 2.6.0)

### ISSUE THREAD

**Issue by InvisibleSmiley** [laminas/laminas-dependency-plugin#61] opened 2024-02-08 14:48 UTC
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no (hopefully?)

#### Summary

Currently this package can only be installed with Composer versions <2.6.0 which bumped the Composer plugin API version to 2.6.0.
Versions prior to 2.3.0 of this package allowed ^2.0 of the composer-plugin-api, but only newer versions added support for PHP 8.2 and 8.3.
Hence, right now you cannot use this package with Composer >= 2.6.0 and PHP >= 8.2.

**Comment by Ocramius** [comment] 2024-02-08 14:50
Duplicate of #59, #58, #46

**Closed as completed by Ocramius** 2024-02-08 14:50 UTC
Labels: Enhancement, Invalid, Won't Fix

**Comment by InvisibleSmiley** [comment] 2024-02-08 15:12
Sorry my bad, didn't read the README
